[package]
name = "libssh2-sys"
version = "0.0.1"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
links = "ssh2"
build = "build.rs"

[lib]
name = "libssh2-sys"
path = "lib.rs"

[dependencies.libz-sys]
  git = "https://github.com/alexcrichton/libz-sys"

[target.i686-apple-darwin.dependencies.openssl-sys]
  git = "https://github.com/alexcrichton/openssl-sys"
[target.x86_64-apple-darwin.dependencies.openssl-sys]
  git = "https://github.com/alexcrichton/openssl-sys"
[target.i686-unknown-linux-gnu.dependencies.openssl-sys]
  git = "https://github.com/alexcrichton/openssl-sys"
[target.x86_64-unknown-linux-gnu.dependencies.openssl-sys]
  git = "https://github.com/alexcrichton/openssl-sys"
[target.i686-unknown-freebsd.dependencies.openssl-sys]
  git = "https://github.com/alexcrichton/openssl-sys"
[target.x86_64-unknown-freebsd.dependencies.openssl-sys]
  git = "https://github.com/alexcrichton/openssl-sys"

[build-dependencies.pkg-config]
git = "https://github.com/alexcrichton/pkg-config-rs"
