language: rust
before_script:
  - ssh-keygen -t rsa -f ~/.ssh/id_rsa -N "" -q
  - eval `ssh-agent -s`
  - ssh-add ~/.ssh/id_rsa
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - telnet localhost 22 &
script:
  - cargo build --verbose
  - cargo test --verbose
  - rustdoc --test README.md -L target
  - cargo doc
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  echo '<meta http-equiv=refresh content=0;url=ssh2/index.html>' > target/doc/index.html &&
  sudo pip install ghp-import &&
  ghp-import -n target/doc &&
  git push -fq https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages &&
  rm target/doc/index.html &&
  mv target/doc . &&
  (curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh)
env:
  global:
    - secure: GXvFl6Bh7nFfuiB/3Gstuo0MlpZGNlw93gdwXhotSb1h3OG8LpiL+SQuDOTzVrPMZ/m+1OoIeydufvbHau0IbqspXddjDMEC3sQfogtudHC0EVrwuj+rctDXq55/HwhQTA73xdVWoe1gvVfm9D/AQ9zFel2ynsS6zlkltRCguEc=
    - secure: eUslk5LsvpQ/kf0AFYVTtYagmo58Um3G6fE79Pb0lkOLEvvk4lTgRZY/vwfggojWsrnU8H1c3hBbbEYnC9tUja7n7ubuZeKjNUKItaIZqTxmvCUYABgXHSHZnuNstEwUq+FzGTLlquZtb5TRu2GsJyf/Yi1gZyjqJYKYfGKwSUc=
notifications:
  email:
    on_success: never
