language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
  - ssh-keygen -t rsa -f ~/.ssh/id_rsa -N "" -q
  - eval `ssh-agent -s`
  - ssh-add ~/.ssh/id_rsa
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - telnet localhost 22 &
script:
  - export CARGO_TARGET_DIR=`pwd`/target
  - cargo build
  - cargo test
  - rustdoc --test README.md -L target
  - cargo run --manifest-path systest/Cargo.toml
  - cargo doc --no-deps
  - cargo doc --no-deps --manifest-path libssh2-sys/Cargo.toml
after_success:
  - travis-cargo --only nightly doc-upload
  - travis-cargo coveralls --no-sudo
notifications:
  email:
    on_success: never
addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
env:
  global:
    secure: UE1kMuctz/nGnlAN5b6dnCDAxY4B71FYBEauFVt/+T7RkhVXzEArf1zepjr+G2mtARqbWy8J93GxTD1ZFU0q8MmYkPRBLnL6ULCr2hmedabtDSuImXFeyBYHIXwRWNcFzsBtBTdBRfKx2YBTjYC0J3LkYaHoYcJEi8O8hW5w6q4=
os:
  - linux
  - osx
