environment:
  matrix:
  - TARGET: i686-pc-windows-gnu
    MINGW: 1
  - TARGET: x86_64-pc-windows-msvc
  - TARGET: i686-pc-windows-msvc
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe"
  - rust-nightly-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - if defined MINGW SET PATH=%PATH%;C:\MinGW\bin;C:\MinGW\msys\1.0\bin
  - rustc -V
  - cargo -V
  - git submodule update --init

build: false

test_script:
  - cargo test --verbose --no-run
