[package]
name = "ssh2"
version = "0.2.15"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
keywords = ["ssh"]
readme = "README.md"
repository = "https://github.com/alexcrichton/ssh2-rs"
homepage = "https://github.com/alexcrichton/ssh2-rs"
documentation = "http://alexcrichton.com/ssh2-rs"
description = """
Bindings to libssh2 for interacting with SSH servers and executing remote
commands, forwarding local ports, etc.
"""

[[test]]
name = "all"

[dependencies]
bitflags = "0.1"
libc = "0.2"
libssh2-sys = { path = "libssh2-sys", version = "0.1.41" }

[target."cfg(unix)".dependencies]
openssl-sys = "0.9"

[dev-dependencies]
tempdir = "0.3"
